packages:
  - .

allowBuilds:
  '@whiskeysockets/baileys': true
  bufferutil: true
  electron: true
  electron-winstaller: true
  esbuild: true
  protobufjs: true
  sharp: true
  wechat-kf-relay: true

onlyBuiltDependencies:
  - wechat-kf-relay

supportedArchitectures:
  cpu: [current, x64, arm64]
  os: [current, darwin, win32]
