export const ADD_PROVIDER_MANAGEMENT_FLAGS_MIGRATION_SQL = `
ALTER TABLE app_providers ADD COLUMN is_added INTEGER NOT NULL DEFAULT 1;
ALTER TABLE app_providers ADD COLUMN is_default INTEGER NOT NULL DEFAULT 0;
`
